<a href="https://colab.research.google.com/github/seungyoonnam/deep-learning/blob/main/05_0921_linnerud_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats  # 과학용 계산 라이브러리
from sklearn.model_selection import train_test_split
from sklearn import metrics
import tensorflow as tf
from tensorflow import keras

In [6]:
from sklearn.datasets import load_linnerud

linnerud = load_linnerud()
print(linnerud.DESCR)

.. _linnerrud_dataset:

Linnerrud dataset
-----------------

**Data Set Characteristics:**

    :Number of Instances: 20
    :Number of Attributes: 3
    :Missing Attribute Values: None

The Linnerud dataset is a multi-output regression dataset. It consists of three
exercise (data) and three physiological (target) variables collected from
twenty middle-aged men in a fitness club:

- *physiological* - CSV containing 20 observations on 3 physiological variables:
   Weight, Waist and Pulse.
- *exercise* - CSV containing 20 observations on 3 exercise variables:
   Chins, Situps and Jumps.

.. topic:: References

  * Tenenhaus, M. (1998). La regression PLS: theorie et pratique. Paris:
    Editions Technic.



In [7]:
linnerud

{'data': array([[  5., 162.,  60.],
        [  2., 110.,  60.],
        [ 12., 101., 101.],
        [ 12., 105.,  37.],
        [ 13., 155.,  58.],
        [  4., 101.,  42.],
        [  8., 101.,  38.],
        [  6., 125.,  40.],
        [ 15., 200.,  40.],
        [ 17., 251., 250.],
        [ 17., 120.,  38.],
        [ 13., 210., 115.],
        [ 14., 215., 105.],
        [  1.,  50.,  50.],
        [  6.,  70.,  31.],
        [ 12., 210., 120.],
        [  4.,  60.,  25.],
        [ 11., 230.,  80.],
        [ 15., 225.,  73.],
        [  2., 110.,  43.]]),
 'feature_names': ['Chins', 'Situps', 'Jumps'],
 'target': array([[191.,  36.,  50.],
        [189.,  37.,  52.],
        [193.,  38.,  58.],
        [162.,  35.,  62.],
        [189.,  35.,  46.],
        [182.,  36.,  56.],
        [211.,  38.,  56.],
        [167.,  34.,  60.],
        [176.,  31.,  74.],
        [154.,  33.,  56.],
        [169.,  34.,  50.],
        [166.,  33.,  52.],
        [154.,  34.,  64.],
        

In [8]:
df = pd.concat([pd.DataFrame(linnerud.data, columns=linnerud.feature_names),
                pd.DataFrame(linnerud.target, columns=linnerud.target_names)],
               axis=1)
df.tail()

Chins  Situps  Jumps  Weight  Waist  Pulse
15   12.0   210.0  120.0   202.0   37.0   62.0
16    4.0    60.0   25.0   176.0   37.0   54.0
17   11.0   230.0   80.0   157.0   32.0   52.0
18   15.0   225.0   73.0   156.0   33.0   54.0
19    2.0   110.0   43.0   138.0   33.0   68.0

In [9]:
#결측치 확인
df.isnull().sum()

Chins     0
Situps    0
Jumps     0
Weight    0
Waist     0
Pulse     0
dtype: int64

In [11]:
#컬럼 확인
df.columns

Index(['Chins', 'Situps', 'Jumps', 'Weight', 'Waist', 'Pulse'], dtype='object')

In [16]:
#X, Y(Class) splitting
x = df.iloc[:,0:4].values
y = df.iloc[:,5].values

In [17]:
x

array([[  5., 162.,  60., 191.],
       [  2., 110.,  60., 189.],
       [ 12., 101., 101., 193.],
       [ 12., 105.,  37., 162.],
       [ 13., 155.,  58., 189.],
       [  4., 101.,  42., 182.],
       [  8., 101.,  38., 211.],
       [  6., 125.,  40., 167.],
       [ 15., 200.,  40., 176.],
       [ 17., 251., 250., 154.],
       [ 17., 120.,  38., 169.],
       [ 13., 210., 115., 166.],
       [ 14., 215., 105., 154.],
       [  1.,  50.,  50., 247.],
       [  6.,  70.,  31., 193.],
       [ 12., 210., 120., 202.],
       [  4.,  60.,  25., 176.],
       [ 11., 230.,  80., 157.],
       [ 15., 225.,  73., 156.],
       [  2., 110.,  43., 138.]])

In [18]:
y

array([50., 52., 58., 62., 46., 56., 56., 60., 74., 56., 50., 52., 64.,
       50., 46., 62., 54., 52., 54., 68.])

In [24]:
np.unique(y)

array([46., 50., 52., 54., 56., 58., 60., 62., 64., 68., 74.])

In [20]:
#Splitting the data into training and test test
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [41]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(4,input_shape=(4,),activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(Adam(lr=0.02),'binary_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_36 (Dense)            (None, 4)                 20        
                                                                 
 dense_37 (Dense)            (None, 4)                 20        
                                                                 
 dense_38 (Dense)            (None, 4)                 20        
                                                                 
 dense_39 (Dense)            (None, 1)                 5         
                                                                 
Total params: 65 (260.00 Byte)
Trainable params: 65 (260.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [43]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=0)
y_pred_class = np.argmax(y_pred,axis=0)

Epoch 1/100
1/1 [==============================] - 0s 239ms/step - loss: -4.7176 - accuracy: 0.0000e+00 - val_loss: -5.5165 - val_accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 235ms/step - loss: -4.7717 - accuracy: 0.0000e+00 - val_loss: -5.5780 - val_accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 140ms/step - loss: -4.8258 - accuracy: 0.0000e+00 - val_loss: -5.6395 - val_accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 184ms/step - loss: -4.8799 - accuracy: 0.0000e+00 - val_loss: -5.7009 - val_accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 163ms/step - loss: -4.9340 - accuracy: 0.0000e+00 - val_loss: -5.7624 - val_accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 53ms/step - loss: -4.9881 - accuracy: 0.0000e+00 - val_loss: -5.8239 - val_accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 36ms/step - loss: -5.0422 - accuracy: 0.0